enable-magisk-update = true

patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"

[YouTube]
build-mode = "both"
excluded-patches = "'Custom branding name for YouTube'"
included-patches = "'Custom header for YouTube' 'MaterialYou' 'Visual preferences icons'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Music]
build-mode = "both"
excluded-patches = "'Custom branding name for YouTube Music' 'Enable Cairo splash animation'"
included-patches = "'Custom header for YouTube Music'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
